version: '2'
services:
    todo-server:
        build: ./backend
        expose:
            - 8080
        ports:
            - 8080:8080
        restart: unless-stopped
        
    todo-client:
        build: ./frontend
        depends_on:
            - backend
        expose:
            - 3000
        ports:
            - 3000:80
        restart: unless-stopped
